#!/usr/bin/env python3
"""
safeguard_forge.py — Analyze .mas/mistakes.jsonl and auto-generate safeguard rules.

Called by masonry-mistake-monitor.js after 5+ new mistake entries accumulate.
Reads the full mistakes.jsonl, detects repeated patterns, and writes (or overwrites)
~/.claude/rules/auto-safeguards.md with actionable safeguard rules.

Idempotent: re-reads the full file and regenerates the output completely each run.
Usage: python3 safeguard_forge.py [path-to-mistakes.jsonl]
"""

import json
import os
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


# ── Pattern counters ──────────────────────────────────────────────────────────

def count_mistake_types(records: list[dict]) -> Counter:
    """Count occurrences of each mistake type."""
    counter: Counter = Counter()
    for record in records:
        mistake_type = record.get("type", "")
        if mistake_type:
            counter[mistake_type] += 1
    return counter


def count_error_keywords(records: list[dict]) -> Counter:
    """Count how many tool_failure records contain BLOCKED in the error snippet."""
    blocked_count = 0
    for record in records:
        if record.get("type") == "tool_failure":
            snippet = record.get("error_snippet", "")
            if "BLOCKED" in snippet:
                blocked_count += 1
    return Counter({"tool_failure_blocked": blocked_count})


# ── Rule generation ───────────────────────────────────────────────────────────

def build_rules(type_counts: Counter, keyword_counts: Counter) -> list[dict]:
    """
    Return a list of rule dicts: {"title": ..., "body": ...}
    based on frequency thresholds.
    """
    rules = []

    if type_counts["git_stash_drop"] >= 2:
        rules.append({
            "title": "Never use `git stash drop` — use `git stash pop`",
            "body": (
                "`git stash drop` permanently destroys the stash entry without restoring your "
                "changes. Always use `git stash pop` to restore **and** remove the stash in one "
                "safe operation. If you need to inspect the stash first, run `git stash show -p` "
                "before deciding to pop or drop."
            ),
        })

    if type_counts["git_reset_hard_dirty"] >= 2:
        rules.append({
            "title": "Check for uncommitted changes before `git reset --hard`",
            "body": (
                "`git reset --hard` with a dirty working tree will permanently discard all "
                "uncommitted modifications. Always run `git status` first. If changes exist, "
                "commit them (`git commit`) or stash them (`git stash`) before resetting."
            ),
        })

    if type_counts["git_push_force_main"] >= 1:
        rules.append({
            "title": "Never force-push to master/main — use a feature branch and PR",
            "body": (
                "Force-pushing to `master` or `main` rewrites shared history and can destroy "
                "teammates' work. Instead: create a feature branch, push the branch, and open a "
                "pull request. If you need to update a stale branch, use `git pull --rebase` "
                "followed by `git push` (no force flag)."
            ),
        })

    if keyword_counts["tool_failure_blocked"] >= 3:
        rules.append({
            "title": "Hook blocks: check hook configuration before retrying",
            "body": (
                "Multiple commands have been blocked by safety hooks. Before retrying a blocked "
                "command, read the block reason carefully — hooks block for good reasons. "
                "Review `masonry/src/hooks/` and `~/.claude/settings.json` hooks sections to "
                "understand which hook fired and why. Never use `--no-verify` to bypass hooks."
            ),
        })

    return rules


# ── Output ─────────────────────────────────────────────────────────────────────

def render_markdown(rules: list[dict], timestamp: str) -> str:
    """Render the rules list to a markdown string."""
    if not rules:
        return (
            f"# Auto-Generated Safeguards\n"
            f"*Last updated: {timestamp} — generated by safeguard_forge.py*\n\n"
            f"No patterns detected yet — not enough mistake data.\n"
        )

    lines = [
        "# Auto-Generated Safeguards",
        f"*Last updated: {timestamp} — generated by safeguard_forge.py*",
        "",
    ]
    for rule in rules:
        lines.append(f"## {rule['title']}")
        lines.append(rule["body"])
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    # Resolve the mistakes file path
    if len(sys.argv) > 1:
        mistakes_path = Path(sys.argv[1]).expanduser().resolve()
    else:
        # Walk up from cwd to find .mas/
        cwd = Path.cwd()
        mistakes_path = None
        for candidate in [cwd, *cwd.parents]:
            p = candidate / ".mas" / "mistakes.jsonl"
            if p.exists():
                mistakes_path = p
                break
        if mistakes_path is None:
            # No mistakes file — write an empty safeguards file and exit cleanly
            records = []
        else:
            records = None  # will be loaded below

    if mistakes_path is not None and mistakes_path.exists():
        records = []
        try:
            with open(mistakes_path, "r", encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        records.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        except OSError:
            records = []
    elif records is None:
        records = []

    type_counts = count_mistake_types(records)
    keyword_counts = count_error_keywords(records)
    rules = build_rules(type_counts, keyword_counts)

    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    content = render_markdown(rules, timestamp)

    # Write to ~/.claude/rules/auto-safeguards.md
    rules_dir = Path.home() / ".claude" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    output_path = rules_dir / "auto-safeguards.md"
    output_path.write_text(content, encoding="utf-8")

    print(f"safeguard_forge: wrote {len(rules)} rule(s) to {output_path}")


if __name__ == "__main__":
    main()
